const express = require('express');
const db      = require('../db');
const { askClaude } = require('../services/claude');
const { authenticate } = require('../middleware/auth');

const router = express.Router();
router.use(authenticate);

const FIFTEEN_DAYS_MS = 15 * 24 * 60 * 60 * 1000;

// ── Static seed questions (fallback / first-run) ───────────
const STATIC_QUESTIONS = {
  'devops-sre': {
    label: 'DevOps / SRE Engineer',
    questions: [
      // SCREENER (5)
      { tier:'screener', q:'How many years of hands-on Kubernetes cluster administration — not just deployment — do you have?', good:'States specific years, mentions production clusters, names cloud provider (EKS/AKS/GKE).', flag:'Says "I know Kubernetes" without mentioning production. Confuses kubectl usage with cluster admin.' },
      { tier:'screener', q:'What CI/CD tool is your primary pipeline today, and what does a typical pipeline you built look like?', good:'Names a specific tool, walks through stages (lint, build, test, deploy), mentions environment promotion.', flag:'Only mentions the tool name without describing what they actually built.' },
      { tier:'screener', q:'Which cloud provider are you strongest in — AWS, Azure, or GCP — and at what certification level?', good:'States one clearly, backs it up with cert name or specific service experience. Self-aware about gaps.', flag:'Claims expertise in all three equally. No certs and no specific service names.' },
      { tier:'screener', q:'Are you comfortable with an on-call rotation? What was the most recent incident you responded to?', good:'Describes a real incident: what broke, how they were paged, how they resolved it, what the postmortem showed.', flag:'Hesitation about on-call. Vague incident description with no specific root cause.' },
      { tier:'screener', q:'Walk me through how you provision infrastructure from scratch — what tools, what order?', good:'Mentions Terraform or Pulumi first, Ansible/Chef for config, container registry, then deployment. Logical sequence.', flag:'Starts with the application rather than infrastructure. No IaC mention.' },
      // TECHNICAL (8)
      { tier:'technical', q:'Explain the difference between a Kubernetes Deployment and a StatefulSet. When would you use each?', good:'Deployment for stateless apps, StatefulSet for databases/queues needing stable network identity and ordered scaling.', flag:'Can only describe Deployment. Blank on StatefulSet or gives incorrect answer.' },
      { tier:'technical', q:'How do you handle secrets management in a Kubernetes environment?', good:'Mentions Vault, AWS Secrets Manager, or Sealed Secrets. Knows not to put secrets in ConfigMaps or env vars in YAML.', flag:'Says "Kubernetes Secrets" without mentioning encryption at rest or external secrets management.' },
      { tier:'technical', q:'Describe how you would set up a blue-green deployment. What are the risks?', good:'Two identical environments, traffic switch at load balancer, rollback by switching back. Risks: DB schema drift, cost of double infra.', flag:'Confuses blue-green with canary. Cannot name the rollback mechanism.' },
      { tier:'technical', q:'What is GitOps and how does it differ from traditional CI/CD?', good:'GitOps: Git is the single source of truth, pull-based (cluster pulls from repo, not push). ArgoCD or FluxCD. Traditional CI/CD is push-based.', flag:'Uses GitOps and CI/CD interchangeably. Cannot name a GitOps tool.' },
      { tier:'technical', q:'How do you monitor a production Kubernetes cluster? What metrics do you alert on first?', good:'Prometheus + Grafana, Datadog, or Dynatrace. Alerts on: node CPU/memory pressure, pod CrashLoopBackOff, API server latency, PVC usage.', flag:'Only mentions CloudWatch or generic monitoring without K8s-specific metrics.' },
      { tier:'technical', q:'You have a Terraform plan that will destroy and recreate a production database. What do you do?', good:'Stop, read the plan carefully, check if lifecycle prevent_destroy is set, take a snapshot, coordinate with team, consider targeted apply or import.', flag:'Would just run the plan. Does not mention backup or lifecycle rules.' },
      { tier:'technical', q:'Explain how you would reduce AWS costs by 30% for a running production environment.', good:'Right-sizing EC2, Reserved Instances or Savings Plans, S3 lifecycle policies, NAT gateway optimization, removing unused EBS volumes, spot instances for non-critical workloads.', flag:'Only mentions "turning off dev environments." No awareness of pricing models.' },
      { tier:'technical', q:'What is the difference between horizontal and vertical pod autoscaling in Kubernetes?', good:'HPA scales replica count based on CPU/memory/custom metrics. VPA adjusts resource requests/limits on existing pods. KEDA for event-driven scaling.', flag:'Only knows HPA. Cannot explain VPA or how to configure scaling thresholds.' },
      // CLIENT-READY (5)
      { tier:'client', q:'Tell me about a production outage you personally led the resolution of. What was your RCA?', good:'Specific incident, timeline, their exact actions, RCA document, preventive measures implemented after.', flag:'Vague story, "the team handled it," no personal ownership, no follow-up action.' },
      { tier:'client', q:'How do you balance the speed of feature delivery with infrastructure stability?', good:'Mentions feature flags, staged rollouts, SLOs/SLAs, error budgets, and conversation with product teams.', flag:'Says "we always prioritize stability" or "developers need to move fast" without nuance.' },
      { tier:'client', q:'Describe the largest infrastructure you have personally managed in terms of nodes and traffic.', good:'Specific numbers: N nodes, X requests/sec, Y TB data. Even if smaller scale, specifics show real ownership.', flag:'Vague ("large scale," "enterprise") without any numbers or specifics.' },
      { tier:'client', q:'What is your experience working with development teams to shift security left?', good:'Mentions SAST/DAST in pipeline, image scanning (Trivy, Snyk), policy-as-code (OPA), pre-commit hooks, developer training.', flag:'Treats security as a separate team responsibility. No tooling knowledge.' },
      { tier:'client', q:'Where do you see the DevOps/SRE space heading in the next 2 years?', good:'Platform engineering, AI-assisted observability, eBPF-based networking, WebAssembly for edge, greater GitOps adoption, FinOps maturity.', flag:'Generic answer. No specific technologies or trends mentioned.' },
    ]
  },
  'cloud-architect': {
    label: 'Cloud Architect',
    questions: [
      { tier:'screener', q:'What is your strongest cloud platform and what is the largest migration project you have led?', good:'Names specific platform, gives scale (X servers, Y TB data, Z applications), timeline, and outcome.', flag:'Claims all three platforms equally. No migration numbers or outcomes.' },
      { tier:'screener', q:'What certifications do you currently hold and when do they expire?', good:'Names specific certs (SAP, Solutions Architect Professional, Azure Architect Expert), expiry dates, and what they are studying next.', flag:'Lists certs from 5+ years ago with no renewals. Cannot describe what the exam tested.' },
      { tier:'screener', q:'Have you designed a multi-account AWS Organization or Azure Management Group structure? For how many accounts?', good:'Specific account count, explains Landing Zone or CAF approach, governance policies, SCPs or Azure Policies.', flag:'Only experience with single-account environments. Cannot describe governance at scale.' },
      { tier:'screener', q:'What is your experience with cloud cost governance and FinOps?', good:'Mentions tagging strategy, cost allocation, showback/chargeback, Reserved Instances, Savings Plans, rightsizing process.', flag:'No structured approach. Only mentions "looking at the bill at the end of the month."' },
      { tier:'screener', q:'Can you describe a situation where your architecture decision was wrong and what you learned?', good:'Specific example, honest about the mistake, concrete lesson, changed approach going forward.', flag:'Cannot think of an example or gives an example where it was clearly someone else\'s fault.' },
      { tier:'technical', q:'Design a highly available, multi-region architecture for a financial services application. Walk me through your decisions.', good:'Active-active vs active-passive choice with justification, Route 53 with health checks, RDS Multi-AZ, cross-region replication, data residency compliance, RPO/RTO targets.', flag:'Generic "put it in multiple regions" without discussing data consistency, failover, or compliance.' },
      { tier:'technical', q:'How do you approach network design in a cloud environment — VPCs, subnets, transit gateways?', good:'Hub-and-spoke with Transit Gateway, private subnets for workloads, public for ALB, VPN or Direct Connect for hybrid, security groups vs NACLs.', flag:'Treats cloud networking like on-premises. Cannot explain Transit Gateway purpose.' },
      { tier:'technical', q:'What is the difference between IaaS, PaaS, and SaaS and when do you choose each?', good:'Clear definitions with real examples. Chooses PaaS to reduce operational burden where possible, IaaS for legacy lift-and-shift, SaaS for commodity functions.', flag:'Textbook definitions only. Cannot explain the operational and cost tradeoffs for a specific scenario.' },
      { tier:'technical', q:'How do you design for compliance in a cloud environment — HIPAA, SOC2, or PCI DSS?', good:'Data classification, encryption at rest and in transit, audit logging (CloudTrail, Azure Monitor), VPC isolation, access reviews, third-party assessments.', flag:'Treats compliance as "a checkbox." No specific control implementation knowledge.' },
      { tier:'technical', q:'What is your approach to disaster recovery — what are RPO and RTO and how do you design for them?', good:'Defines RPO (data loss tolerance) and RTO (recovery time tolerance). Matches DR strategy (warm standby, pilot light, active-active) to business requirements.', flag:'Cannot define RPO and RTO. No awareness of cost-versus-recovery-speed tradeoffs.' },
      { tier:'technical', q:'How do you handle database migrations with zero downtime in a cloud environment?', good:'Blue-green database switchover, logical replication, shadow writes, feature flags to control traffic cutover, rollback plan.', flag:'"We take a maintenance window." No zero-downtime strategy.' },
      { tier:'technical', q:'Explain how you would architect a data lake on AWS or Azure.', good:'S3 or ADLS Gen2 for storage, Glue or ADF for ETL, Athena or Synapse for query, Lake Formation or Unity Catalog for governance, tiered storage for cost.', flag:'Confuses data lake with data warehouse. Cannot explain the raw/curated/refined zone pattern.' },
      { tier:'client', q:'How do you communicate complex architectural decisions to non-technical stakeholders?', good:'Uses business impact language (cost, risk, time), diagrams at appropriate abstraction level, ties decisions to business goals.', flag:'Leads with technical detail. Cannot translate architecture to business value.' },
      { tier:'client', q:'Describe a time you had to push back on a client or stakeholder\'s architectural preference.', good:'Specific example, explains their reasoning clearly, offered alternatives, outcome.', flag:'Always agrees with stakeholders. Cannot give a specific pushback example.' },
      { tier:'client', q:'What is your approach to technology standardization versus best-of-breed tool selection?', good:'Balances standardization (operational simplicity, support, cost) against best-of-breed (competitive advantage, developer preference). Context-dependent answer.', flag:'Always standardizes OR always picks best-of-breed without situational reasoning.' },
      { tier:'client', q:'How do you stay current with cloud platform changes — there are hundreds of new services per year?', good:'Names specific sources: AWS re:Invent talks, Azure Friday, cloud provider blogs, AWS/Azure weekly newsletters, experimentation in personal accounts.', flag:'Vague answer. No specific sources or learning habits mentioned.' },
      { tier:'client', q:'What would your first 30 days look like joining a new client as their cloud architect?', good:'Discovery (existing architecture, current pain points, business roadmap), stakeholder interviews, architecture review, quick wins, 90-day roadmap proposal.', flag:'Jumps straight to making changes. No discovery or listening phase mentioned.' },
    ]
  },
  'java-backend': {
    label: 'Senior Java Developer',
    questions: [
      { tier:'screener', q:'What version of Java are you currently working with and what features from Java 17 or later do you use daily?', good:'Names Java version, mentions records, sealed classes, pattern matching, virtual threads (21+), or text blocks as appropriate.', flag:'Still on Java 8 with no awareness of modern features. Cannot name anything past streams and lambdas.' },
      { tier:'screener', q:'What Spring Boot version are you on and how do you structure a typical microservice?', good:'Names Spring Boot 3.x, describes package structure, controller-service-repository pattern, exception handling, and Spring Security configuration.', flag:'Only knows Spring MVC. Cannot describe microservice boundaries or exception handling strategy.' },
      { tier:'screener', q:'How do you handle database transactions across multiple microservices?', good:'Knows two-phase commit is problematic. Mentions Saga pattern (choreography vs orchestration), outbox pattern, eventual consistency.', flag:'Says "just use @Transactional across services." Does not know Saga pattern.' },
      { tier:'screener', q:'What is your experience with Kafka or other message brokers?', good:'Producer-consumer setup, consumer groups, offset management, exactly-once semantics, dead letter queues, schema registry.', flag:'Has only "read about Kafka." Cannot describe a producer-consumer setup they built.' },
      { tier:'screener', q:'How do you approach API versioning in a REST service?', good:'URI versioning (/v1/, /v2/), header versioning, or content negotiation. Knows tradeoffs. Has sunset policy for old versions.', flag:'No versioning strategy. Changes existing API endpoints directly.' },
      { tier:'technical', q:'Explain the difference between @Component, @Service, @Repository, and @Controller in Spring.', good:'All are @Component specializations. @Repository adds exception translation. @Service is semantic. @Controller enables MVC. Knows when to use each.', flag:'Treats them as interchangeable. Cannot explain @Repository exception translation.' },
      { tier:'technical', q:'How does Spring Security work and how would you implement JWT authentication?', good:'Filter chain, SecurityContext, JWT parsing in OncePerRequestFilter, stateless session, method-level security with @PreAuthorize.', flag:'Only configured Spring Security from a tutorial. Cannot describe the filter chain.' },
      { tier:'technical', q:'What is the N+1 query problem and how do you solve it in JPA/Hibernate?', good:'N+1: loading parent entities then querying each child individually. Fix: JOIN FETCH, @BatchSize, EntityGraph, or DTO projection.', flag:'Does not know the term. Cannot describe lazy vs eager loading tradeoffs.' },
      { tier:'technical', q:'How do you write unit tests for a Spring Boot service that has external dependencies?', good:'@ExtendWith(MockitoExtension), @MockBean, Mockito.when(), @WebMvcTest for controllers, @DataJpaTest for repositories, @SpringBootTest only for integration.', flag:'Only does @SpringBootTest for everything. No awareness of test slices or unit vs integration test boundaries.' },
      { tier:'technical', q:'Explain circuit breaker pattern and how you implement it in a Java microservices environment.', good:'Resilience4j or Hystrix, states (closed/open/half-open), fallback methods, configuring failure rate thresholds, combining with retry.', flag:'Has heard of it but never implemented. Cannot name a library.' },
      { tier:'technical', q:'How do you profile and resolve a memory leak in a Java production service?', good:'Heap dump via jmap or JFR, analyze with VisualVM or Eclipse MAT, look for retained references, object finalization issues, connection pool leaks.', flag:'Restart the service. No tooling knowledge for root cause analysis.' },
      { tier:'technical', q:'What is reactive programming in Java and when would you choose it over traditional blocking?', good:'Project Reactor, Mono/Flux, non-blocking I/O, backpressure, use case: high-concurrency I/O-bound with low thread count. Not always better.', flag:'Thinks reactive is always faster. Cannot explain backpressure or when NOT to use it.' },
      { tier:'technical', q:'How do you manage database schema changes in a CI/CD pipeline?', good:'Flyway or Liquibase, versioned migration scripts, tested in pipeline before deployment, backward-compatible migrations for zero-downtime.', flag:'Manual SQL scripts run by a DBA. No automated migration tool.' },
      { tier:'client', q:'Describe the largest-scale Java system you have worked on — how many requests per second, how many services?', good:'Specific numbers, explains their role, bottlenecks they solved, how the system evolved.', flag:'Vague about scale. Cannot quantify load or their specific contribution.' },
      { tier:'client', q:'How do you approach code review — what do you look for beyond correctness?', good:'Performance implications, security vulnerabilities, test coverage, API design, naming clarity, thread safety, exception handling, observability.', flag:'Only checks if the code compiles and does what the ticket says.' },
      { tier:'client', q:'Tell me about a technical debt decision you made and how you managed it.', good:'Specific trade-off, business context for why they took the debt, how they tracked it, whether it was eventually paid.', flag:'Claims to never take technical debt or cannot give a specific example.' },
      { tier:'client', q:'How do you handle disagreements with a tech lead or architect about a design decision?', good:'States their position clearly with evidence, listens to the counterargument, willing to defer with documented dissent, escalates appropriately if needed.', flag:'Always defers. Or always insists. No middle ground or professional conflict resolution.' },
      { tier:'client', q:'Where is the Java ecosystem heading over the next two years?', good:'Virtual threads (Project Loom GA), GraalVM native image growth, Jakarta EE vs Spring competition, Quarkus/Micronaut for cloud-native, AI SDK integration.', flag:'No awareness of Project Loom or cloud-native Java trends.' },
    ]
  },
  'python-dev': {
    label: 'Senior Python Developer',
    questions: [
      { tier:'screener', q:'What Python version are you working in and what async/await or type annotation features do you use?', good:'Python 3.10+, uses type hints throughout, asyncio or trio, dataclasses or Pydantic models, walrus operator, structural pattern matching.', flag:'Still on Python 2 or early 3.x. No type hints. Cannot explain why async/await matters.' },
      { tier:'screener', q:'What is your primary web framework — FastAPI, Django, or Flask — and why did you or your team choose it?', good:'Clear preference with reasoning. FastAPI for performance and automatic OpenAPI docs. Django for ORM and admin. Flask for simplicity. Knows tradeoffs.', flag:'Knows only one framework and cannot explain why it was chosen over alternatives.' },
      { tier:'screener', q:'How do you manage Python dependencies and environments across a team?', good:'pyproject.toml with Poetry or uv, Docker for environment consistency, pinned requirements with pip-compile, virtual environments per project.', flag:'requirements.txt with unpinned versions. No containerization for dev environment consistency.' },
      { tier:'screener', q:'What is the GIL and how does it affect your architecture decisions?', good:'GIL allows only one thread to execute Python bytecode at a time. CPU-bound: use multiprocessing or async. I/O-bound: asyncio or threading is fine.', flag:'Does not know what GIL stands for or why it matters for concurrency.' },
      { tier:'screener', q:'How do you structure a large Python project — how do you avoid circular imports and keep modules clean?', good:'Package-based structure, dependency injection, interface layers, lazy imports where necessary, clear separation of domain logic from infrastructure.', flag:'Everything in one or two files. No awareness of circular import causes or solutions.' },
      { tier:'technical', q:'Explain list comprehensions vs generator expressions vs map/filter. When do you choose which?', good:'List comp: when you need all results in memory. Generator: lazy evaluation for large datasets. map/filter: functional style, but comprehensions are more Pythonic.', flag:'Uses list comprehensions for everything, including iterating over 10GB files.' },
      { tier:'technical', q:'How do you write async code in Python that does not block the event loop?', good:'await on all I/O operations, use asyncio.gather for concurrent tasks, run CPU-bound work in executor (loop.run_in_executor), avoid time.sleep (use asyncio.sleep).', flag:'Uses threading with asyncio. Calls blocking functions directly in async functions.' },
      { tier:'technical', q:'How do you design a RESTful API with FastAPI — walk through authentication, validation, and error handling.', good:'OAuth2PasswordBearer or JWT dependency, Pydantic models for request/response validation, custom exception handlers, HTTPException with detail, OpenAPI docs auto-generated.', flag:'Can describe endpoints but not authentication middleware or validation strategy.' },
      { tier:'technical', q:'How do you test a Python service that has external HTTP calls and database queries?', good:'pytest with pytest-asyncio, httpx.AsyncClient for HTTP mocking, SQLAlchemy in-memory SQLite or test database, monkeypatch or unittest.mock, factory_boy for fixtures.', flag:'Only integration tests against live services. No mocking strategy.' },
      { tier:'technical', q:'What is your approach to Celery or background task processing in Python?', good:'Celery with Redis or RabbitMQ broker, task serialization, retry logic with exponential backoff, chord/chain for complex workflows, monitoring with Flower.', flag:'Never used background tasks. Or confuses Celery with cron jobs.' },
      { tier:'technical', q:'How do you handle database migrations in a Python web application?', good:'Alembic for SQLAlchemy, Django migrations for Django ORM. Auto-generate with --autogenerate, review before applying, backward-compatible for zero-downtime.', flag:'Manual SQL. No migration tool. Cannot explain how to handle migration conflicts in a team.' },
      { tier:'technical', q:'Explain how Python memory management works and how you debug a memory leak.', good:'Reference counting plus cyclic garbage collector. Profile with memory_profiler, tracemalloc, or objgraph. Common culprits: circular references, large globals, unclosed resources.', flag:'Cannot explain reference counting. No profiling tool knowledge.' },
      { tier:'technical', q:'How do you secure a Python API — what OWASP risks are most relevant and how do you mitigate them?', good:'SQL injection (ORM + parameterized), IDOR (authorization checks per request), broken auth (JWT expiry, refresh tokens), rate limiting, input sanitization.', flag:'Only mentions "use HTTPS." No OWASP awareness.' },
      { tier:'client', q:'Describe the highest-traffic Python service you have run in production. How many requests per second?', good:'Specific numbers, how they handled scaling (uvicorn workers, gunicorn, async), what they optimized, monitoring setup.', flag:'Cannot quantify. Vague about production experience.' },
      { tier:'client', q:'How do you approach performance optimization in Python — what do you profile first?', good:'Profile before optimizing (cProfile, py-spy). Check I/O first (usually the bottleneck), then algorithmic complexity, then memory. Benchmarks before and after.', flag:'"Python is slow so we rewrote it in Go." No profiling discipline. Premature optimization.' },
      { tier:'client', q:'Tell me about a Python codebase you inherited that was in bad shape. What did you do?', good:'Assessment first, added tests before refactoring, incremental improvement, documented decisions, got team buy-in.', flag:'Rewrote everything immediately. Or gave up. No pragmatic approach.' },
      { tier:'client', q:'How do you keep up with the Python ecosystem given how fast it moves?', good:'PEPs for language changes, Real Python, PyCon talks, Hynek Schlawack\'s blog, Python Weekly newsletter, experimenting with new features in personal projects.', flag:'No specific sources. Generic "I read documentation."' },
      { tier:'client', q:'Where is Python heading in the next two years?', good:'No-GIL (PEP 703), better type inference tools, Pydantic v2 ecosystem, AI/ML tooling growth, PyScript for browser, faster interpreters (PyPy, mypyc).', flag:'No awareness of PEP 703 or current ecosystem trends.' },
    ]
  },
  'fullstack': {
    label: 'Fullstack Developer (React + Node)',
    questions: [
      { tier:'screener', q:'What React version are you on and which hooks do you use most — beyond useState and useEffect?', good:'React 18+, uses useCallback, useMemo for optimization, useRef for DOM/interval, useContext for global state, custom hooks for logic reuse.', flag:'Only knows useState and useEffect. No awareness of concurrent features or optimization hooks.' },
      { tier:'screener', q:'What is your Node.js backend experience — Express, Fastify, or NestJS?', good:'Clear primary framework, explains their service structure, middleware pattern, error handling, and why they chose it.', flag:'Only frontend. No real Node.js production experience.' },
      { tier:'screener', q:'How do you manage state in a large React application — Redux, Zustand, or React Query?', good:'Differentiates server state (React Query/SWR) from client state (Zustand/Redux). Knows when global state is actually needed vs prop drilling fix.', flag:'Uses Redux for everything including local UI state. Or says "I just use useState for everything."' },
      { tier:'screener', q:'What is TypeScript and how deeply do you use it on both frontend and backend?', good:'Uses generics, utility types (Partial, Pick, Omit, Record), discriminated unions, strict mode, zod for runtime validation. Full-stack TypeScript.', flag:'Knows basic type annotations. Avoids generics. Uses "any" frequently.' },
      { tier:'screener', q:'How do you handle authentication in a fullstack app — where does the token live and why?', good:'HttpOnly cookie (prevents XSS access to token), CSRF protection, refresh token rotation, server-side session invalidation option. Knows why localStorage is risky.', flag:'Stores JWT in localStorage. Does not know what XSS means in this context.' },
      { tier:'technical', q:'Explain React\'s reconciliation algorithm and how keys affect it.', good:'Virtual DOM diffing, fiber architecture in React 18, key prop identifies elements across re-renders, avoid index as key when list order changes.', flag:'Cannot explain reconciliation. Uses array index as key always.' },
      { tier:'technical', q:'How do you optimize a React application that has slow re-renders?', good:'React DevTools Profiler to identify, useMemo/useCallback to memoize, React.memo for pure components, code splitting with lazy/Suspense, virtualization for long lists.', flag:'Adds useMemo everywhere without profiling. Cannot use React DevTools Profiler.' },
      { tier:'technical', q:'How do you design a REST API with Node.js — how do you handle validation, errors, and auth middleware?', good:'Zod or Joi for input validation, centralized error handler middleware, JWT middleware, rate limiting, structured error responses with status codes.', flag:'No input validation. Error handling is try/catch in each route with no centralization.' },
      { tier:'technical', q:'Explain the difference between server-side rendering, client-side rendering, and static generation. When does each matter?', good:'CSR: SPA, SEO-unfriendly, fast after initial load. SSR: SEO-friendly, TTFB higher, Next.js getServerSideProps. SSG: best performance, content must be static, ISR for dynamic.', flag:'Cannot explain SEO implications or when to use each. Thinks Next.js is always better.' },
      { tier:'technical', q:'How do you prevent SQL injection and XSS in a fullstack application?', good:'SQL: parameterized queries, never string concatenation. XSS: React escapes by default, avoid dangerouslySetInnerHTML, Content-Security-Policy header, sanitize user input.', flag:'Does not know what SQL injection is. Relies on React "handling security."' },
      { tier:'technical', q:'How do you implement real-time features — WebSockets, Server-Sent Events, or polling?', good:'WebSockets for bidirectional real-time (chat, collaborative), SSE for unidirectional server-push (notifications, live feeds), polling as fallback. Socket.io for simplicity.', flag:'Always uses polling. Cannot explain WebSocket vs SSE tradeoffs.' },
      { tier:'technical', q:'How do you test a fullstack application — what is your testing pyramid?', good:'Unit (pure functions with Jest), integration (React Testing Library + MSW for API mocks), E2E (Cypress or Playwright for critical paths). Knows not to over-test with E2E.', flag:'Only manual testing. Or only E2E tests which are slow and brittle.' },
      { tier:'technical', q:'How do you handle database access from Node.js — ORM, query builder, or raw SQL?', good:'Prisma or TypeORM for rapid development with type safety, Knex.js for query builder control, raw SQL for complex queries. Knows connection pooling and migration tools.', flag:'Uses raw SQL everywhere without connection pooling. Or uses an ORM without understanding what queries it generates.' },
      { tier:'client', q:'Describe the largest frontend codebase you have maintained. How many components, developers?', good:'Specific numbers, explains how they managed complexity (component library, design system, Storybook), team conventions.', flag:'Vague. Cannot describe the architecture or their specific ownership.' },
      { tier:'client', q:'How do you approach accessibility in your frontend work?', good:'Semantic HTML, ARIA labels, keyboard navigation, focus management, color contrast ratios, screen reader testing with NVDA or VoiceOver, Lighthouse audits.', flag:'"Our design team handles that." No personal ownership of accessibility.' },
      { tier:'client', q:'How do you handle the coordination between frontend and backend during API design?', good:'API contract first (OpenAPI spec), mock APIs for parallel development, versioning strategy, breaking change communication process.', flag:'Frontend waits for backend to finish. No parallel development strategy.' },
      { tier:'client', q:'What is your approach to frontend performance — Core Web Vitals and bundle size?', good:'LCP, FID, CLS metrics, Lighthouse CI in pipeline, code splitting, image optimization (next/image or similar), lazy loading, CDN, tree shaking.', flag:'Does not know Core Web Vitals. No performance monitoring in production.' },
      { tier:'client', q:'Where is the React/Node ecosystem heading in the next two years?', good:'React Server Components, Server Actions, Bun replacing Node in some cases, Vite dominance, edge computing (Deno Deploy, Cloudflare Workers), AI code generation impact on developer workflow.', flag:'No awareness of React Server Components or current ecosystem direction.' },
    ]
  },
  'ml-ai': {
    label: 'ML / AI Engineer',
    questions: [
      { tier:'screener', q:'What ML frameworks are you strongest in — TensorFlow, PyTorch, or JAX — and what have you built with them?', good:'Clear primary with specific projects. If PyTorch, mentions torch.nn, DataLoader, training loop. If TensorFlow, Keras API, TF Serving. Specific architectures built.', flag:'Names framework without describing a real model they trained and deployed.' },
      { tier:'screener', q:'Explain the difference between supervised, unsupervised, and reinforcement learning with an example of each you have worked on.', good:'Supervised: classification/regression with labeled data. Unsupervised: clustering, anomaly detection. RL: reward-based agent. Real examples for each.', flag:'Textbook definitions only. Cannot give a project example for each type.' },
      { tier:'screener', q:'How do you take a model from a Jupyter notebook to production?', good:'Refactor to modular Python, Docker container, REST API with FastAPI or TorchServe/TF Serving, CI/CD pipeline, monitoring for data drift and model drift.', flag:'Has only done Jupyter work. No idea how to serve a model or monitor it in production.' },
      { tier:'screener', q:'What is your experience with LLMs — have you fine-tuned, RAG-implemented, or built agents?', good:'Specific: fine-tuned with LoRA/QLoRA, built RAG with LangChain or LlamaIndex + vector DB (Pinecone, Weaviate), or built tool-calling agents. Knows tradeoffs between each approach.', flag:'Has only used the ChatGPT UI. No programmatic LLM experience.' },
      { tier:'screener', q:'How do you handle class imbalance in a training dataset?', good:'SMOTE, class weights in loss function, oversampling/undersampling, stratified splits, precision-recall instead of accuracy, focal loss for extreme imbalance.', flag:'Does not know what class imbalance is. Uses accuracy as the only metric.' },
      { tier:'technical', q:'Explain the transformer architecture — what is self-attention and why does it matter?', good:'Query-Key-Value attention, parallel sequence processing, context window, multi-head attention captures different relationship types, position encodings for order.', flag:'Says "it is like RNN but better." Cannot explain attention mechanism math or purpose.' },
      { tier:'technical', q:'What is the difference between fine-tuning, LoRA, and RAG — when do you choose each?', good:'Full fine-tuning: expensive, for behavior change. LoRA: efficient parameter update, for style/domain adaptation. RAG: no training, for factual grounding on external knowledge. Cost-accuracy tradeoff.', flag:'Thinks RAG and fine-tuning are the same thing. Cannot explain LoRA concept.' },
      { tier:'technical', q:'How do you evaluate an LLM-based application — what metrics do you use?', good:'RAGAS for RAG (faithfulness, answer relevance, context precision), BLEU/ROUGE for generation, human eval, LLM-as-judge, red-teaming for safety, latency and cost per query.', flag:'Only uses accuracy or perplexity. No awareness of LLM-specific eval frameworks.' },
      { tier:'technical', q:'What is your MLOps stack — how do you track experiments, version models, and monitor production?', good:'MLflow or W&B for experiment tracking, DVC for data versioning, model registry, Prometheus/Grafana or Arize for production monitoring, data drift detection with Evidently.', flag:'No experiment tracking. Re-runs experiments from scratch. No production monitoring.' },
      { tier:'technical', q:'Explain overfitting and the techniques you use to prevent it.', good:'Regularization (L1/L2/dropout), early stopping, data augmentation, cross-validation, reducing model complexity, more training data, batch normalization.', flag:'Only knows to use dropout. Cannot explain why overfitting happens mechanically.' },
      { tier:'technical', q:'How do you optimize inference latency for a deployed model?', good:'Quantization (INT8/FP16), model pruning, ONNX export, TensorRT, batching requests, caching frequent queries, smaller distilled model for edge cases.', flag:'No inference optimization experience. Deploys full-precision model without profiling.' },
      { tier:'technical', q:'What is your experience with vector databases and embedding models?', good:'Pinecone, Weaviate, Qdrant, pgvector, or FAISS. Embedding models: OpenAI, Sentence Transformers, Cohere. Knows cosine similarity, HNSW indexing, chunking strategies.', flag:'Vague about vector DBs. Cannot explain what an embedding represents or why cosine similarity is used.' },
      { tier:'technical', q:'How do you handle prompt injection and other LLM security risks in production?', good:'Input sanitization, system prompt protection, output validation, rate limiting, content moderation layer, separation of user input from system instructions.', flag:'No awareness of prompt injection. Treats LLM output as trusted.' },
      { tier:'client', q:'Tell me about the highest-impact ML model you shipped to production. What was the business metric improvement?', good:'Specific model, specific metric (revenue uplift, cost reduction, error rate), before-after comparison, deployment scale.', flag:'Vague. Cannot quantify business impact. Only academic projects.' },
      { tier:'client', q:'How do you explain a model\'s prediction to a non-technical stakeholder?', good:'SHAP values, LIME, feature importance, business-friendly analogies, visualization, what the model would have predicted if one feature changed.', flag:'"I can\'t explain it, it\'s a black box." No interpretability tooling knowledge.' },
      { tier:'client', q:'How do you handle bias in ML models — detection and mitigation?', good:'Disaggregated metrics by demographic group, AIF360 or Fairlearn tools, data collection improvements, fairness constraints in training, regular audits post-deployment.', flag:'No awareness of algorithmic bias or fairness metrics beyond overall accuracy.' },
      { tier:'client', q:'How do you stay current with the AI/ML field given the pace of change?', good:'arXiv daily (cs.LG, cs.CL), Hugging Face blog, Papers With Code, specific researchers on Twitter/X, replicating 1-2 papers per month.', flag:'Generic answer. No specific papers or researchers mentioned.' },
      { tier:'client', q:'Where is the ML/AI engineering field going in the next two years?', good:'Multimodal models, agentic AI going mainstream, smaller on-device models, synthetic data at scale, model merging, mechanistic interpretability, AI safety becoming an engineering discipline.', flag:'Only mentions "AI is getting smarter." No technical trend awareness.' },
    ]
  },
  'cybersecurity': {
    label: 'Cybersecurity Engineer',
    questions: [
      { tier:'screener', q:'What is your primary domain in security — AppSec, CloudSec, SOC/IR, or GRC — and what certs do you hold?', good:'Clear primary domain with depth, secondary awareness. Certs: CISSP, CEH, OSCP, CISM, AWS Security Specialty, CompTIA Security+. Knows what each validates.', flag:'Claims all domains equally. No certs or certs from 10+ years ago with no renewals.' },
      { tier:'screener', q:'Walk me through your incident response process when you receive a high-severity alert at 2am.', good:'Triage alert (true/false positive), contain (isolate affected systems), investigate (logs, memory dump), eradicate (remove threat), recover, document, postmortem.', flag:'Vague. No structured IR methodology. Cannot describe containment steps.' },
      { tier:'screener', q:'What SIEM tools have you used in production and what kind of detection rules did you write?', good:'Splunk, QRadar, Sentinel, or Elastic SIEM. Wrote SPL/KQL queries, correlation rules for lateral movement, brute force detection, privilege escalation alerts.', flag:'Only watched SIEM dashboards. Never wrote a detection rule from scratch.' },
      { tier:'screener', q:'What compliance frameworks have you worked under — SOC2, PCI DSS, HIPAA, NIST?', good:'Names specific frameworks with specific control implementations (not just awareness). Has been through an audit.', flag:'Only knows framework names. Cannot describe specific controls they implemented.' },
      { tier:'screener', q:'How do you stay current with the threat landscape?', good:'MITRE ATT&CK updates, CVE feeds, Krebs on Security, SANS ISC, vendor threat intel, CTF competitions, bug bounty participation.', flag:'Generic "I read security news." No specific sources or active practice.' },
      { tier:'technical', q:'Explain the MITRE ATT&CK framework and how you use it operationally.', good:'Tactics, techniques, sub-techniques. Maps detections to ATT&CK coverage, identifies gaps, threat-hunts using technique patterns, tabletop exercises use it for scenarios.', flag:'Knows the name but cannot explain tactics vs techniques. Never used it for detection engineering.' },
      { tier:'technical', q:'How would you detect lateral movement in an enterprise network?', good:'Unusual SMB/RPC traffic, Pass-the-Hash/Pass-the-Ticket patterns, Kerberoasting in Windows event logs, new admin shares, behavioral baselines for user movement.', flag:'Cannot explain lateral movement techniques. Relies only on perimeter controls.' },
      { tier:'technical', q:'What is the difference between authentication and authorization — how do you test each for vulnerabilities?', good:'AuthN: who you are (test: brute force, credential stuffing, MFA bypass). AuthZ: what you can do (test: IDOR, privilege escalation, JWT manipulation, BOLA).', flag:'Uses the terms interchangeably. Cannot describe IDOR testing methodology.' },
      { tier:'technical', q:'How do you approach cloud security in AWS or Azure — what are the top misconfigurations you look for?', good:'S3 public ACLs, overly permissive IAM roles (star permissions), security groups open to 0.0.0.0/0, unencrypted EBS/S3, no CloudTrail, publicly exposed metadata service.', flag:'No cloud security experience. Applies on-premises security model to cloud.' },
      { tier:'technical', q:'Explain how you would conduct a penetration test against a web application.', good:'Recon, OWASP Top 10 testing (SQLi, XSS, IDOR, broken auth, XXE, SSRF), Burp Suite, automated scanning + manual verification, report with CVSS scores and remediation.', flag:'Cannot describe a methodology. Only uses automated scanners without manual validation.' },
      { tier:'technical', q:'How does certificate management work and what are the risks of poor cert hygiene?', good:'PKI chain, Let\'s Encrypt vs enterprise CA, cert expiry monitoring (often causes outages), wildcard cert risks, certificate pinning, HSTS, OCSP stapling.', flag:'Certificates are "just renewed when they expire." No PKI understanding.' },
      { tier:'technical', q:'What is your experience with threat modeling — have you used STRIDE, PASTA, or DREAD?', good:'STRIDE for spoofing/tampering/repudiation/info disclosure/DoS/elevation. Used early in design phase, data flow diagrams, identifies threats before code is written.', flag:'Threat modeling is done by architects, not security engineers. Cannot explain STRIDE.' },
      { tier:'technical', q:'How do you handle a zero-day vulnerability affecting a production system?', good:'Assess impact and exploitation likelihood, apply compensating controls (WAF rules, network segmentation, feature disable), monitor closely, apply vendor patch in maintenance window, communicate to stakeholders.', flag:'Wait for vendor patch. No compensating controls while patch is awaited.' },
      { tier:'client', q:'Tell me about the most serious security incident you personally responded to. What was the impact and outcome?', good:'Specific incident type (ransomware, data breach, insider threat), their role, actions taken, business impact quantified, lessons learned.', flag:'Vague. "I cannot share details due to NDA" without any generalized description.' },
      { tier:'client', q:'How do you communicate security risks to C-level executives who do not have a technical background?', good:'Business impact language (revenue risk, regulatory fines, reputational damage), risk matrix with likelihood vs impact, cost of control vs cost of breach, avoids jargon.', flag:'Uses technical language with leadership. Cannot translate CVE scores to business risk.' },
      { tier:'client', q:'How do you prioritize a vulnerability backlog when everything seems high priority?', good:'CVSS score + exploitability in the wild (CISA KEV catalog) + asset criticality + blast radius. Patch critical-exploited-in-wild first regardless of CVSS.', flag:'Patches highest CVSS score first regardless of exploitability or asset value.' },
      { tier:'client', q:'What is your philosophy on security versus developer velocity?', good:'Security as enabler, not gatekeeper. Shift left with automation (SAST in pipeline, pre-commit hooks), guardrails not gates, developer education, blameless culture.', flag:'"Security always comes first, no exceptions." Or "developers should be able to move without security slowing them down." No nuance.' },
      { tier:'client', q:'Where is the cybersecurity field heading in the next two years?', good:'AI-powered threat detection and adversarial AI, identity-first security, supply chain security (SBOM), zero trust maturity, cloud security posture management, quantum-resistant cryptography preparation.', flag:'Generic "hackers are getting smarter." No specific technology or methodology trends.' },
    ]
  },
  'salesforce': {
    label: 'Salesforce Developer',
    questions: [
      { tier:'screener', q:'What certifications do you currently hold and when did you get them?', good:'Platform Developer I and II, specific dates, studying for next cert. Knows what each tests (PD1: core platform, PD2: advanced Apex and patterns).', flag:'Only Admin cert. No developer certs. Or certs from 5+ years ago with no Trailhead maintenance.' },
      { tier:'screener', q:'Walk me through the difference between a trigger, a flow, and a process builder — when do you use each?', good:'Triggers: complex logic, bulkified Apex. Flow: declarative automation, now preferred over Process Builder. Process Builder: legacy, being retired. Knows Salesforce official recommendation to migrate to Flow.', flag:'Uses Process Builder for everything. Does not know Salesforce is deprecating it.' },
      { tier:'screener', q:'What is governor limits and how do you design around them?', good:'100 SOQL queries per transaction, 150 DML statements, heap size. Bulkification, moving queries out of loops, platform cache, async processing for heavy operations.', flag:'Hits governor limits in production. Cannot explain why SOQL in a loop is a problem.' },
      { tier:'screener', q:'What is your experience with Lightning Web Components versus Aura?', good:'Prefers LWC (modern, faster, web standards-based). Can explain when Aura is still needed. Has migrated Aura components to LWC.', flag:'Still building Aura components exclusively. No LWC experience.' },
      { tier:'screener', q:'Describe your experience with Salesforce integrations — REST API, SOAP, or middleware?', good:'Named credential setup, REST callouts in Apex, Connected Apps, OAuth flows, middleware (MuleSoft, Boomi, Informatica), platform events for async integration.', flag:'Only experience with import/export tools (Data Loader). No programmatic integration.' },
      { tier:'technical', q:'Explain the Salesforce security model — profiles, permission sets, roles, and sharing rules.', good:'Profiles control object access. Permission sets extend profiles. Roles control record visibility (org-wide defaults + role hierarchy). Sharing rules open up OWD restrictions. Criteria-based sharing for complex scenarios.', flag:'Uses profiles for everything. Cannot explain the difference between permission sets and profiles.' },
      { tier:'technical', q:'How do you write a bulkified Apex trigger and what happens if you do not?', good:'One trigger per object, collection-based processing (Map/List), no SOQL/DML in loops, use trigger handler pattern (separate class), test with 200+ records.', flag:'Loops in triggers. SOQL inside for loops. Tests with only one record.' },
      { tier:'technical', q:'What is the Apex test framework and what code coverage is required for deployment?', good:'75% minimum, but aims for 90%+. @isTest, Test.startTest/stopTest for async, System.assert not just coverage, mock callouts with HttpCalloutMock, TestDataFactory for test data.', flag:'Writes tests only to reach 75%. Does not assert anything. Uses production data in tests.' },
      { tier:'technical', q:'How do you implement a CI/CD pipeline for Salesforce development?', good:'Salesforce DX, scratch orgs for development, GitHub Actions or Copado, SFDX CLI, metadata API, change sets only for small orgs, source-driven development.', flag:'Still using change sets for all deployments. No Salesforce DX knowledge.' },
      { tier:'technical', q:'What is your experience with Salesforce CPQ or Revenue Cloud?', good:'Product catalog, price rules, quote line editor, approval workflows, order management, integration with billing systems.', flag:'Has not used CPQ. Or has only used it as an end user, not as a developer.' },
      { tier:'technical', q:'How do you handle large data volumes in Salesforce — what are the limits?', good:'SOQL query optimizer, indexed fields, skinny tables, Bulk API for large data operations, Data Skew issues in ownership, archiving strategies.', flag:'Does not know about Data Skew. No awareness of Bulk API vs REST API for large operations.' },
      { tier:'technical', q:'Explain Platform Events and how they compare to Streaming API.', good:'Platform Events: publish-subscribe messaging on Salesforce platform, high-volume option, replay ID for missed events. Streaming API: PushTopic for record changes, CometD protocol.', flag:'Never implemented event-driven architecture on Salesforce. Cannot explain asynchronous messaging.' },
      { tier:'technical', q:'How do you implement Salesforce Communities or Experience Cloud?', good:'Experience Builder, guest user licenses, Digital Experiences, community templates, headless communities with Salesforce APIs, content management.', flag:'No Experience Cloud knowledge. Only works on internal Salesforce users.' },
      { tier:'client', q:'Tell me about the most complex Apex class or LWC you have ever built. What made it challenging?', good:'Specific component, specific challenge (governor limits, complex data model, real-time requirements), specific solution.', flag:'Vague. Cannot describe technical complexity with specific details.' },
      { tier:'client', q:'How do you approach a Salesforce implementation that has years of technical debt?', good:'Audit with Salesforce Optimizer, prioritize by business impact, incremental modernization (Flow migration, LWC adoption), documentation, testing before changes.', flag:'Rewrite everything at once. No incremental strategy.' },
      { tier:'client', q:'How do you stay current with Salesforce releases — there are three per year?', good:'Release notes review for each release, pre-release org testing, Trailhead maintenance modules, Salesforce Ben blog, Admin/Dev preview orgs, user groups.', flag:'Waits to hear from colleagues what changed. No proactive release readiness.' },
      { tier:'client', q:'What is your experience with multi-org or multi-cloud Salesforce architectures?', good:'Connected Orgs, Cross-org data sharing with data federation, Salesforce+Tableau, Salesforce+MuleSoft, org strategy decisions (multi-org risks vs single-org complexity).', flag:'Only single-org experience. No awareness of multi-org considerations.' },
      { tier:'client', q:'Where is the Salesforce platform heading in the next two years?', good:'Einstein Copilot and AI everywhere, Data Cloud integration, Hyperforce expansion, more automation migration from Process Builder/Workflow Rules, Revenue Cloud growth.', flag:'No awareness of Einstein Copilot or Salesforce AI direction.' },
    ]
  },
  'scrum-master': {
    label: 'Scrum Master / Agile Coach',
    questions: [
      { tier:'screener', q:'What certifications do you hold — CSM, PSM, SAFe — and how do you view the difference between them?', good:'PSM from Scrum.org (knowledge-based exam) vs CSM from Scrum Alliance (attendance-based). SAFe for enterprise scaling. Has a view on which they found most valuable and why.', flag:'Only CSM from a 2-day class. Cannot explain the difference in rigor between certifications.' },
      { tier:'screener', q:'How many teams have you been a Scrum Master for simultaneously and how did you manage competing needs?', good:'Specific number (2-4 is common, 5+ is spreading thin). Describes how they prioritized across teams, what they delegated, and what suffered.', flag:'Has only served one team. No experience balancing multiple team needs.' },
      { tier:'screener', q:'Tell me about a time the team wanted to skip the retrospective because they were under deadline pressure. What did you do?', good:'Held a shorter retro rather than skipping. Explained the value, made it time-boxed (30 min), focused on one actionable item. Protected the ceremony.', flag:'Agreed to skip the retrospective. Or forced a long retro and created resentment.' },
      { tier:'screener', q:'How do you measure the health of a Scrum team beyond velocity?', good:'Retrospective action item follow-through rate, team happiness scores, lead time, cycle time, defect escape rate, sprint goal achievement rate (not just story count).', flag:'Only measures velocity. Treats velocity as the primary health indicator.' },
      { tier:'screener', q:'What is the difference between a Scrum Master and a Project Manager?', good:'SM: servant leader, no command authority, focuses on team health and process. PM: traditionally has authority over resources and budget, output-focused. SM protects the team; PM represents external stakeholders.', flag:'Says "Scrum Master is just a more modern title for Project Manager." Does not understand servant leadership.' },
      { tier:'technical', q:'How do you facilitate a sprint planning session for a team that consistently over-commits?', good:'Review historical velocity, focus on capacity (not commitment), break stories to smaller items for better estimation, use past sprint data as anchor, create psychological safety around saying "no."', flag:'Lets the team commit to whatever they want and accepts that sprints will fail. No data-driven planning.' },
      { tier:'technical', q:'What techniques do you use when a retrospective becomes repetitive or unproductive?', good:'New formats (Start/Stop/Continue, 4Ls, Speedboat, Lean Coffee), different facilitation tools (Miro, FunRetro), rotating facilitator, anonymous input, follow up on previous action items first.', flag:'Always uses the same format. Cannot name more than one retrospective technique.' },
      { tier:'technical', q:'How do you handle a team member who is not following Scrum — for example, not updating the board?', good:'1-on-1 conversation to understand why, remove the obstacle if there is one (too many tools, unclear process), team agreement on Definition of Done, coaching not enforcing.', flag:'Escalates to the manager immediately. Or ignores it.' },
      { tier:'technical', q:'Explain how you would implement Kanban in a team that currently uses Scrum. When would you recommend Kanban over Scrum?', good:'Kanban better for operations/support teams with unpredictable incoming work. Scrum for product development with defined sprint goals. Scrumban as a transition. WIP limits are the key Kanban practice.', flag:'Treats Scrum and Kanban as interchangeable. Cannot explain WIP limits.' },
      { tier:'technical', q:'How do you work with a Product Owner who is unavailable or writes poor user stories?', good:'Set clear expectations about PO availability requirements, backlog refinement sessions scheduled in advance, user story writing workshops, INVEST criteria coaching, escalate to management if PO does not engage.', flag:'Writes the user stories themselves. Or accepts poor stories and blames the PO during retro.' },
      { tier:'technical', q:'What is your experience with scaled Agile frameworks — SAFe, LeSS, or Nexus?', good:'Specific framework experience, what problems it solved, what overhead it added, PI Planning or Nexus Sprint Planning specifics, ART or tribe structure.', flag:'Only single-team Scrum. No experience scaling beyond one team.' },
      { tier:'technical', q:'How do you track and communicate team progress to stakeholders who are not in the daily standup?', good:'Sprint review for stakeholder demo, team-level metrics (burndown, velocity trend, sprint goal achievement), executive summary in plain language, roadmap transparency in a wiki or portfolio tool.', flag:'Stakeholders attend standups. Or stakeholders only find out at the sprint review.' },
      { tier:'technical', q:'How do you help a team improve their Definition of Done over time?', good:'Start with what they can consistently meet, add criteria incrementally after retros, make it visible, ensure everyone understands each criterion, tie it to quality outcomes not just checkboxes.', flag:'Definition of Done is set once and never revisited. Or is used as a compliance checklist.' },
      { tier:'client', q:'Tell me about the most dysfunctional team you ever coached. What did you try and what worked?', good:'Specific dysfunction (conflict, low trust, dependency on a hero developer), specific interventions (team working agreements, conflict resolution, pair programming), specific outcome.', flag:'Has never worked with a dysfunctional team. Or gives a vague answer with no specific interventions.' },
      { tier:'client', q:'How do you handle conflict between a developer and the Product Owner about priority?', good:'Facilitates conversation between them, reminds the team of sprint goal as the anchor, escalates to stakeholders if the PO cannot make a decision, protects the team from thrash.', flag:'Takes a side. Or avoids the conflict entirely.' },
      { tier:'client', q:'How do you measure your own effectiveness as a Scrum Master?', good:'Team improvement over time (retro action completion rate, reduced blockers, lower defect rate, team asking for less help over time as they self-organize), 360 feedback.', flag:'Measures effectiveness by whether standups run on time. Or cannot articulate how to measure it.' },
      { tier:'client', q:'What is the future of Agile and Scrum — is it still relevant in 2025 and beyond?', good:'Scrum remains relevant but AI-assisted development changes sprint cadence and story sizing. Continuous delivery reduces the value of 2-week sprints for some teams. Agile values remain; ceremonies are adapting.', flag:'Says Agile is dying. Or says nothing has changed and Scrum is perfect as-is.' },
      { tier:'client', q:'How do you coach a team that has been doing "Scrum-but" — doing Scrum in name only?', good:'Inspect where they deviate and why (understand root causes, not just symptoms), prioritize one change at a time, show value before enforcing compliance, use retros to surface the gaps.', flag:'Forces full Scrum compliance immediately. Or accepts the status quo without trying to improve.' },
    ]
  },
  'platform-engineer': {
    label: 'Platform Engineer',
    questions: [
      { tier:'screener', q:'How do you define Platform Engineering versus DevOps — and what does your internal developer platform look like?', good:'DevOps is a culture/practice. Platform Engineering builds the tooling and abstractions that enable DevOps. Their IDP (Internal Developer Platform) has: self-service environment provisioning, golden paths, developer portal (Backstage), CI/CD templates.', flag:'Uses Platform Engineering and DevOps interchangeably. Cannot describe an IDP.' },
      { tier:'screener', q:'What is your experience with Backstage or other developer portals?', good:'Backstage setup, catalog entities, software templates (scaffolder), TechDocs integration, custom plugins, adoption challenges and how they drove it.', flag:'Knows the name but never implemented Backstage. No developer portal experience.' },
      { tier:'screener', q:'How do you measure platform success — what are your platform SLOs?', good:'Developer experience metrics: deployment frequency, DORA metrics (lead time, MTTR, change failure rate), platform reliability (99.9%+ uptime), onboarding time to first deploy, adoption rate of golden paths.', flag:'No platform metrics. Success is "developers are happy." No quantitative measurement.' },
      { tier:'screener', q:'How do you handle the tension between standardization (golden paths) and developer autonomy?', good:'Golden paths as the easiest path, not the only path. Paved road metaphor. Escape hatches documented. Consult model for exceptions. Community of practice to evolve standards.', flag:'Enforces standardization rigidly. Or gives developers complete autonomy with no shared standards.' },
      { tier:'screener', q:'What is your Kubernetes cluster strategy — multi-cluster or single cluster — and why?', good:'Multi-cluster for: isolation (prod/staging), regional availability, workload separation, compliance. Single cluster: simpler, lower cost. Their choice driven by specific requirements.', flag:'No opinion. Only experience with single cluster. Cannot explain when multi-cluster is justified.' },
      { tier:'technical', q:'How do you implement self-service environment provisioning for development teams?', good:'Crossplane or Terraform Cloud, Kubernetes operators, Backstage software templates, GitOps workflow (PR triggers environment creation), RBAC for team isolation.', flag:'Manual environment provisioning by the platform team. No self-service capability.' },
      { tier:'technical', q:'Explain how you manage secrets across multiple Kubernetes clusters and environments.', good:'External Secrets Operator + AWS Secrets Manager/Vault, sealed secrets for GitOps, never store secrets in Git, rotation strategy, audit logging on secret access.', flag:'Kubernetes native Secrets with base64 encoding. No external secrets management.' },
      { tier:'technical', q:'How do you implement and enforce security policies across a Kubernetes platform?', good:'OPA/Gatekeeper or Kyverno for policy-as-code, admission controllers, image signing (Cosign + Rekor), network policies, pod security admission, runtime security (Falco).', flag:'Only RBAC. No policy-as-code. No runtime threat detection.' },
      { tier:'technical', q:'Describe your observability platform — how do you achieve full-stack visibility?', good:'Metrics (Prometheus), logs (Loki or ELK), traces (Jaeger or Tempo), Grafana as unified frontend, OpenTelemetry for instrumentation standard, alerting with PagerDuty integration.', flag:'Individual team tools with no unified platform. Cannot describe a trace from browser to database.' },
      { tier:'technical', q:'How do you manage Kubernetes upgrades across a fleet of clusters with zero downtime?', good:'Test in non-prod first, rolling upgrade with node pools, PodDisruptionBudgets to protect workloads, validate deprecated APIs (pluto), blue-green cluster approach for major versions.', flag:'In-place upgrade of all nodes simultaneously. No PDB awareness. No API deprecation check.' },
      { tier:'technical', q:'How do you implement chargeback or showback for platform costs?', good:'Kubecost or OpenCost for K8s cost allocation, tag-based cost allocation in cloud provider, team-level dashboards, anomaly alerts, rightsizing recommendations surfaced to teams.', flag:'No cost visibility. Platform costs are a black box to development teams.' },
      { tier:'technical', q:'What is your experience with eBPF and how do you use it in a platform context?', good:'Cilium for networking and security, Pixie for zero-instrumentation observability, Tetragon for runtime security, Falco with eBPF probe. Understands eBPF runs in kernel safely sandboxed.', flag:'No eBPF experience or awareness. Cannot explain what eBPF is in simple terms.' },
      { tier:'technical', q:'How do you manage database provisioning as part of your platform?', good:'Crossplane for cloud database provisioning, operator-based (RDS, CloudNativePG), connection pooling (PgBouncer), database per service for microservices, schema migration as part of deployment pipeline.', flag:'Databases are managed separately from the platform. No self-service DB provisioning.' },
      { tier:'client', q:'Tell me about the most impactful platform improvement you shipped. How did you measure developer satisfaction before and after?', good:'Specific improvement (reduced deployment time, self-service environments, improved observability), specific before/after metrics, developer NPS or survey data.', flag:'Cannot quantify impact. Vague improvement without measurement.' },
      { tier:'client', q:'How do you drive adoption of platform capabilities when developers resist change?', good:'Executive sponsorship, champion developers in each team, show not tell (demos of time saved), migration support from platform team, not enforcing but incentivizing, community of practice.', flag:'Mandates adoption from the top. Or gives up when facing resistance.' },
      { tier:'client', q:'How do you handle a critical platform outage that affects all development teams?', good:'Immediately communicate impact and ETA to all affected teams, incident commander role, dedicated war room, status page update, postmortem with blameless culture, platform SLO credit.', flag:'Fixes the issue quietly. No stakeholder communication during the incident.' },
      { tier:'client', q:'How do you prioritize the platform roadmap between reliability, new features, and developer experience?', good:'DORA metrics as north star, quarterly planning with developer team input, dedicated reliability capacity (20-30% of team), product-thinking applied to platform.', flag:'Reactive roadmap. Prioritizes whatever the loudest stakeholder requests.' },
      { tier:'client', q:'Where is Platform Engineering heading in the next two years?', good:'AI-assisted platform operations (AIOps), Internal Developer Portals becoming standard, GitOps and platform APIs replacing manual processes, platform engineering as a product discipline with own P&L accountability, WASM for edge platform extension.', flag:'No awareness of IDP trends or AI integration into platform engineering.' },
    ]
  },
  'dba': {
    label: 'Database Administrator (DBA)',
    questions: [
      { tier:'screener', q:'What database platforms are you strongest in and at what scale have you managed them?', good:'Names 2-3 platforms with specific scale (TB of data, TPS, number of databases under management). Clear primary with honest secondary.', flag:'Claims all databases equally. Cannot give specific scale numbers.' },
      { tier:'screener', q:'Walk me through your backup and recovery strategy for a production PostgreSQL database.', good:'pg_basebackup + WAL archiving (point-in-time recovery), backup to S3 with lifecycle policy, tested restores monthly, RTO and RPO defined, pgBackRest or Barman for enterprise.', flag:'pg_dump only. No WAL archiving. Never tested a restore.' },
      { tier:'screener', q:'How do you approach performance tuning when a slow query is reported in production?', good:'Query execution plan (EXPLAIN ANALYZE), look for Seq Scans on large tables, missing indexes, inefficient joins, statistics staleness (VACUUM ANALYZE), connection pool exhaustion.', flag:'Adds an index to every column that appears in a WHERE clause. No EXPLAIN ANALYZE usage.' },
      { tier:'screener', q:'What is your experience with high availability setups — replication, clustering, failover?', good:'PostgreSQL streaming replication with repmgr or Patroni, automatic failover, read replicas for scaling, connection pooler (PgBouncer) for connection management.', flag:'Single-instance databases only. No replication experience.' },
      { tier:'screener', q:'How do you handle database security — who should have access to production and how is it granted?', good:'Principle of least privilege, role-based access, no application connecting as superuser, TLS for connections, column-level security for sensitive data, audit logging, regular access review.', flag:'Application connects as the database superuser. No audit trail.' },
      { tier:'technical', q:'Explain VACUUM and autovacuum in PostgreSQL — why does it matter and when do you tune it?', good:'VACUUM reclaims space from dead tuples created by MVCC, prevents transaction ID wraparound. Autovacuum tuning: cost delay, scale factor, nap time. Tables with high update rates need aggressive autovacuum settings.', flag:'Knows VACUUM runs automatically but cannot explain MVCC, dead tuples, or why bloat happens.' },
      { tier:'technical', q:'How do you identify and fix index bloat in PostgreSQL?', good:'pg_stat_user_indexes, pgstattuple extension, REINDEX CONCURRENTLY for live environments, pg_squeeze for zero-downtime bloat removal, autovacuum tuning to prevent recurrence.', flag:'REINDEX with table lock. No awareness of CONCURRENTLY option. Cannot explain why indexes bloat.' },
      { tier:'technical', q:'Describe how you would migrate a large table with zero downtime.', good:'pg_repack or pg_squeeze for online repack, logical replication for parallel copy, blue-green table approach, foreign key defer, application-level dual-write during migration.', flag:'Takes a maintenance window. No zero-downtime strategy.' },
      { tier:'technical', q:'How do you approach connection pooling and what are the risks of too many database connections?', good:'PgBouncer in transaction mode for short-lived connections, connection limits per role, max_connections tuning, monitoring active vs idle connections, shared_buffers impact.', flag:'No connection pooler. Application opens unlimited connections. Does not understand max_connections.' },
      { tier:'technical', q:'What is your experience with partitioning large tables and when do you use it?', good:'Range, list, or hash partitioning. PostgreSQL declarative partitioning. Benefits: partition pruning in queries, faster VACUUM on partitions, easier archiving. When: tables over 100M+ rows or time-series data.', flag:'Never partitioned a table. Cannot explain query planning benefit of partition pruning.' },
      { tier:'technical', q:'How do you monitor a database cluster in production — what are your key metrics?', good:'Query latency (pg_stat_statements), replication lag (pg_stat_replication), lock waits (pg_locks), autovacuum activity, cache hit ratio, WAL generation rate, connection utilization.', flag:'Only monitors disk space and CPU. No query-level or replication monitoring.' },
      { tier:'technical', q:'What is your experience with Oracle RAC or Data Guard?', good:'RAC for active-active HA with shared storage, Data Guard for physical standby (ADG for reads), switchover vs failover, redo log shipping, protection modes.', flag:'Oracle experience without RAC. Cannot explain the difference between switchover and failover.' },
      { tier:'technical', q:'How do you handle schema migrations in a CI/CD pipeline with zero downtime?', good:'Flyway or Liquibase, backward-compatible migrations (add before drop), expand-contract pattern, feature flags to control new column usage, test migrations in staging first.', flag:'Manual DDL changes in production. No migration tool. Takes downtime for schema changes.' },
      { tier:'client', q:'Tell me about the largest database incident you personally resolved. What was the root cause?', good:'Specific incident (bloat, replication lag, runaway query, wraparound risk), their diagnostic process, root cause, resolution, and preventive measures.', flag:'Vague. Cannot describe a specific root cause or their diagnostic methodology.' },
      { tier:'client', q:'How do you communicate database performance issues and capacity planning to non-technical stakeholders?', good:'Business impact language (response time degradation = X% revenue impact, storage growth rate = budget needed by date), capacity forecasts in plain language.', flag:'Sends raw pg_stat_statements output to stakeholders. Cannot translate technical metrics to business impact.' },
      { tier:'client', q:'How do you stay current with database technology — PostgreSQL releases major versions annually?', good:'PostgreSQL release notes, pganalyze blog, Citus Data blog, PGDG mailing lists, testing new versions in sandbox, attending PGConf.', flag:'Generic "I read documentation." No specific sources or version upgrade testing process.' },
      { tier:'client', q:'What is your philosophy on NoSQL versus relational databases — how do you choose?', good:'Relational for: transactions, relationships, ad-hoc queries. NoSQL for: schema flexibility, horizontal scale, specific access patterns (time series, document, key-value). Not "NoSQL for scale" by default.', flag:'Always uses relational. Or says "NoSQL is faster." No situational reasoning.' },
      { tier:'client', q:'Where is the database landscape heading in the next two years?', good:'PostgreSQL as default choice growing, distributed PostgreSQL (Citus, CockroachDB, Neon), AI workload-optimized databases (pgvector, vector DBs), serverless databases, database-as-code with Terraform.', flag:'No awareness of pgvector, distributed PostgreSQL, or current trends.' },
    ]
  },
};

// ── Seed static questions into DB on first run ─────────────
async function seedIfEmpty() {
  const { rows } = await db.query('SELECT COUNT(*) FROM interview_questions');
  if (parseInt(rows[0].count) > 0) return;
  console.log('[interview] Seeding static questions into DB...');
  for (const [roleId, data] of Object.entries(STATIC_QUESTIONS)) {
    await db.query(
      `INSERT INTO interview_questions (role_id, role_label, questions, refresh_source)
       VALUES ($1, $2, $3, 'static')
       ON CONFLICT (role_id) DO NOTHING`,
      [roleId, data.label, JSON.stringify(data.questions)]
    );
  }
  console.log('[interview] Seeded', Object.keys(STATIC_QUESTIONS).length, 'roles');
}

// ── Claude refresh prompt for one role ─────────────────────
async function refreshRoleWithClaude(roleId, roleLabel) {
  const prompt = `You are an expert IT technical recruiter trainer for the US market.
Generate 18 phone screening questions for the role: "${roleLabel}"

Base these questions on what top US tech companies and IT staffing firms are CURRENTLY asking in phone screens and first-round interviews in 2025:
- Amazon, Google, Microsoft, Meta (Big Tech)
- JPMorgan Chase, Goldman Sachs, Capital One (Finance Tech)
- TEKsystems, Insight Global, Robert Half (IT Staffing)
- Accenture, Deloitte, Cognizant (Consulting)

Return ONLY a JSON array of exactly 18 objects. Start with [ and end with ]. No markdown:
[
  {
    "tier": "screener",
    "q": "question text here",
    "good": "what a strong answer looks like — 1-2 sentences",
    "flag": "what a weak or fake answer looks like — 1-2 sentences"
  }
]

RULES:
- Exactly 5 objects with tier "screener" (quick phone filter — yes/no quality)
- Exactly 8 objects with tier "technical" (validates real hands-on depth)
- Exactly 5 objects with tier "client" (questions clients ask in first round)
- Every "good" and "flag" must be specific and actionable — not generic
- Questions must reflect CURRENT tools and practices for ${roleLabel} in 2025
- Do not use placeholder text`;

  const data = await askClaude(prompt, 2500);
  const questions = Array.isArray(data) ? data : (data && typeof data === 'object' ? Object.values(data).find(v => Array.isArray(v)) : null);
  if (!questions || questions.length < 15) throw new Error('Claude returned invalid question set');
  return questions;
}

// ── GET /api/interview — get all roles + questions ─────────
router.get('/', async (req, res, next) => {
  try {
    await seedIfEmpty();
    const { rows } = await db.query('SELECT * FROM interview_questions ORDER BY role_id');

    // Background refresh for any role older than 15 days (non-blocking)
    const staleRoles = rows.filter(r => {
      const age = Date.now() - new Date(r.refreshed_at).getTime();
      return age > FIFTEEN_DAYS_MS && r.refresh_source !== 'static';
    });
    if (staleRoles.length > 0) {
      setImmediate(async () => {
        for (const role of staleRoles) {
          try {
            const questions = await refreshRoleWithClaude(role.role_id, role.role_label);
            await db.query(
              `UPDATE interview_questions SET questions=$1, refreshed_at=NOW(), refresh_source='claude' WHERE role_id=$2`,
              [JSON.stringify(questions), role.role_id]
            );
            console.log('[interview] Auto-refreshed:', role.role_id);
          } catch (e) { console.warn('[interview] Auto-refresh failed for', role.role_id, e.message); }
        }
      });
    }

    res.json(rows.map(r => ({
      roleId:       r.role_id,
      roleLabel:    r.role_label,
      questions:    r.questions,
      refreshedAt:  r.refreshed_at,
      refreshSource:r.refresh_source,
    })));
  } catch (err) { next(err); }
});

// ── POST /api/interview/refresh/:roleId — admin refresh ────
router.post('/refresh/:roleId', async (req, res, next) => {
  if (req.user.role !== 'admin') return res.status(403).json({ error: 'Admin only' });
  try {
    const { roleId } = req.params;
    const { rows } = await db.query('SELECT role_label FROM interview_questions WHERE role_id=$1', [roleId]);
    if (!rows[0]) return res.status(404).json({ error: 'Role not found' });
    const questions = await refreshRoleWithClaude(roleId, rows[0].role_label);
    await db.query(
      `UPDATE interview_questions SET questions=$1, refreshed_at=NOW(), refresh_source='claude' WHERE role_id=$2`,
      [JSON.stringify(questions), roleId]
    );
    res.json({ ok: true, count: questions.length, refreshedAt: new Date() });
  } catch (err) { next(err); }
});

// ── POST /api/interview/refresh-all — admin refresh all ────
router.post('/refresh-all', async (req, res, next) => {
  if (req.user.role !== 'admin') return res.status(403).json({ error: 'Admin only' });
  const results = [];
  const { rows } = await db.query('SELECT role_id, role_label FROM interview_questions ORDER BY role_id');
  for (const role of rows) {
    try {
      const questions = await refreshRoleWithClaude(role.role_id, role.role_label);
      await db.query(
        `UPDATE interview_questions SET questions=$1, refreshed_at=NOW(), refresh_source='claude' WHERE role_id=$2`,
        [JSON.stringify(questions), role.role_id]
      );
      results.push({ roleId: role.role_id, ok: true, count: questions.length });
    } catch (e) {
      results.push({ roleId: role.role_id, ok: false, error: e.message });
    }
  }
  res.json(results);
});

module.exports = router;
